undertaker: link explicitly against libpthread
This avoids a compilation failure on Ubuntu 14.10 (utopic):

g++   undertaker.o libparser.a ../picosat/libpicosat.a  -lboost_system -lboost_regex -lboost_filesystem -lboost_thread -lPuma -o undertaker
/usr/bin/ld: libparser.a(ModelContainer.o): undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
<builtin>: recipe for target 'undertaker' failed

A bugfix in libstdc++ requires explicit linking of libpthread when
threads of libstdc++ are used (std::async in our case).
( https://gcc.gnu.org/ml/gcc-patches/2014-08/msg01366.html )

Change-Id: Ideffb5ede8a6ed48518b1096bdfe7cbda2d0cb9a